# Generated by Django 4.1 on 2022-08-16 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('watt', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.datetime(2022, 8, 17, 5, 29, 10, 870265))),
            ],
            options={
                'db_table': 'index',
            },
        ),
    ]
