# Generated by Django 4.1 on 2022-08-18 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_alter_entries_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 1, 37, 40, 128498)),
        ),
    ]
